import { Download, ExternalLink, Plus, Printer, Save, Search } from "lucide-react";
import { useMemo, useState, type FormEvent, type ReactNode } from "react";
import { createActivityApi, createEnterpriseApi, createEntrepreneurApi, createFeeApi, createInspectionApi, createTemplateApi, createUserApi, getUserErrorMessage, saveSettingsApi, updateTemplateStatusApi, updateUserStatusApi } from "../../api";
import { useApp } from "../../app/providers";
import { Button, EmptyState, Modal, PageHeader, SearchField, StatusBadge } from "../../components/ui";
import type { ModuleKey, Usuario } from "../../types";

type Row = { id: string; cells: ReactNode[] };

const registryConfig: Partial<Record<ModuleKey, { title: string; description: string; columns: string[] }>> = {
  empreendedores: { title: "Empreendedores", description: "Pessoas físicas e jurídicas vinculadas aos processos.", columns: ["Tipo", "Nome", "Documento", "Contato", "Endereço"] },
  empreendimentos: { title: "Empreendimentos", description: "Unidades, atividades e localização ambiental.", columns: ["Nome", "Proprietário", "Município", "Porte", "Potencial", "Localização"] },
  atividades: { title: "Atividades", description: "Catálogo municipal de atividades licenciáveis.", columns: ["Código", "Descrição", "Porte", "Potencial", "Licenças"] },
  taxas: { title: "Taxas", description: "Valores por atividade, licença e porte.", columns: ["Atividade", "Licença", "Porte", "Valor"] },
  usuarios: { title: "Usuários", description: "Contas, perfis e vínculos de acesso.", columns: ["Nome", "E-mail", "Perfil", "Status", "Último acesso"] },
  modelos: { title: "Modelos de documentos", description: "Conteúdo e variáveis usadas nos documentos oficiais.", columns: ["Nome", "Tipo", "Status", "Prévia"] },
  fiscalizacao: { title: "Fiscalização", description: "Agenda operacional de vistorias e ações de campo.", columns: ["Processo", "Tipo", "Fiscal", "Data", "Coordenadas", "Status"] }
};

export function RegistryPage({ type }: { type: ModuleKey }) {
  const { state, session, refresh } = useApp(); const config = registryConfig[type]; const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  if (!config || !session) return null;
  const rows: Row[] = type === "empreendedores" ? state.empreendedores.map((item) => ({ id: item.id, cells: [item.tipo, item.nome, maskDocument(item.documento), item.email, item.endereco] }))
    : type === "empreendimentos" ? state.empreendimentos.map((item) => ({ id: item.id, cells: [item.nome, state.empreendedores.find((entry) => entry.id === item.empreendedorId)?.nome ?? "-", item.municipio, item.porte, item.potencial, item.latitude ? <a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${item.latitude}&mlon=${item.longitude}`}>Abrir mapa <ExternalLink /></a> : "-"] }))
    : type === "atividades" ? state.atividades.map((item) => ({ id: item.id, cells: [item.codigo, item.descricao, item.porte, item.potencial, item.licencas.join(", ")] }))
    : type === "taxas" ? state.taxas.map((item) => ({ id: item.id, cells: [state.atividades.find((entry) => entry.id === item.atividadeId)?.descricao ?? "-", item.licenca, item.porte, money(item.valor)] }))
    : type === "usuarios" ? state.usuarios.map((item) => ({ id: item.id, cells: [item.nome, item.email, item.perfil, <StatusBadge>{item.ativo ? "Ativo" : "Inativo"}</StatusBadge>, item.ultimoAcesso, <Button variant="ghost" disabled={item.id === session.userId} onClick={async () => { if (!confirm(`${item.ativo ? "Desativar" : "Ativar"} ${item.nome}?`)) return; await updateUserStatusApi(session.token, item.id, !item.ativo); await refresh(); }}>{item.ativo ? "Desativar" : "Ativar"}</Button>] }))
    : type === "modelos" ? state.modelos.map((item) => ({ id: item.id, cells: [item.nome, item.tipo, <StatusBadge>{item.ativo ? "Ativo" : "Inativo"}</StatusBadge>, item.conteudo.slice(0, 90), session.perfil === "Administrador" ? <Button variant="ghost" onClick={async () => { if (!confirm(`${item.ativo ? "Desativar" : "Ativar"} este modelo?`)) return; await updateTemplateStatusApi(session.token, item.id, !item.ativo); await refresh(); }}>{item.ativo ? "Desativar" : "Ativar"}</Button> : null] }))
    : state.fiscalizacoes.map((item) => ({ id: item.id, cells: [state.processos.find((entry) => entry.id === item.processoId)?.numero ?? "-", item.tipo, item.fiscal, item.data, item.gps || "-", <StatusBadge>{item.status ?? "Agendada"}</StatusBadge>] }));
  const filtered = rows.filter((row) => row.cells.map(String).join(" ").toLowerCase().includes(query.toLowerCase()));
  const canCreate = type === "atividades" || type === "taxas" || type === "usuarios" ? session.perfil === "Administrador" : type === "fiscalizacao" ? ["Administrador", "Analista"].includes(session.perfil) : ["Administrador", "Analista", "Empreendedor"].includes(session.perfil);
  const columns = [...config.columns, ...(["usuarios", "modelos"].includes(type) ? ["Ações"] : [])];
  return <><PageHeader title={config.title} description={config.description} actions={canCreate ? <Button onClick={() => setOpen(true)}><Plus />Adicionar</Button> : null} /><div className="registry-toolbar"><SearchField value={query} onChange={setQuery} placeholder={`Pesquisar em ${config.title.toLowerCase()}`} /><span>{filtered.length} registro(s)</span></div>{filtered.length ? <div className="data-table"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{filtered.map((row) => <tr key={row.id}>{row.cells.map((cell, index) => <td data-label={columns[index]} key={index}>{cell}</td>)}</tr>)}</tbody></table></div> : <EmptyState />}{open ? <RegistryForm type={type} onClose={() => setOpen(false)} /> : null}</>;
}

function RegistryForm({ type, onClose }: { type: ModuleKey; onClose(): void }) {
  const { state, session, refresh } = useApp(); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [personType, setPersonType] = useState<"PF" | "PJ">("PJ"); const [role, setRole] = useState<Usuario["perfil"]>("Analista");
  if (!session) return null;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (saving) return; const data: Record<string, string> = {}; new FormData(event.currentTarget).forEach((value, key) => { data[key] = String(value); }); setSaving(true); setError(""); try {
    if (type === "empreendedores") await createEntrepreneurApi(session.token, { ...data, tipo: personType });
    else if (type === "empreendimentos") await createEnterpriseApi(session.token, data, data.empreendedorId ?? "", data.atividadeId ?? "", state.atividades.find((item) => item.id === data.atividadeId));
    else if (type === "atividades") await createActivityApi(session.token, data);
    else if (type === "taxas") await createFeeApi(session.token, data, data.atividadeId ?? "");
    else if (type === "usuarios") await createUserApi(session.token, data, role, data.empreendedorId);
    else if (type === "modelos") await createTemplateApi(session.token, data, data.tipo as "Licença");
    else if (type === "fiscalizacao") await createInspectionApi(session.token, data, data.processoId ?? "", data.fiscalId);
    await refresh(); onClose();
  } catch (cause) { setError(getUserErrorMessage(cause)); } finally { setSaving(false); } };
  return <Modal title={`Adicionar ${registryConfig[type]?.title ?? "registro"}`} onClose={onClose}><form className="typed-form" onSubmit={submit}>
    {type === "empreendedores" ? <><fieldset className="segmented"><legend>Tipo de pessoa</legend><button type="button" className={personType === "PF" ? "active" : ""} onClick={() => setPersonType("PF")}>Pessoa física</button><button type="button" className={personType === "PJ" ? "active" : ""} onClick={() => setPersonType("PJ")}>Pessoa jurídica</button></fieldset><Field name="nome" label={personType === "PF" ? "Nome completo" : "Razão social"} required /><Field name={personType === "PF" ? "cpf" : "cnpj"} label={personType} required inputMode="numeric" /><Field name="responsavelLegal" label="Representante legal" /><Field name="telefone" label="Telefone" required inputMode="tel" /><Field name="email" label="E-mail" required type="email" /><Field name="endereco" label="Endereço" required wide /></> : null}
    {type === "empreendimentos" ? <><Select name="empreendedorId" label="Proprietário" options={state.empreendedores.map((item) => [item.id, item.nome])} /><Select name="atividadeId" label="Atividade" options={state.atividades.map((item) => [item.id, item.descricao])} /><Field name="nome" label="Nome" required /><Field name="endereco" label="Endereço" required /><Field name="municipio" label="Município" defaultValue="Buriti - MA" /><Field name="area" label="Área em hectares" type="number" /><Field name="latitude" label="Latitude" type="number" /><Field name="longitude" label="Longitude" type="number" /><Field name="porte" label="Porte" /><Field name="potencial" label="Potencial poluidor" /><Field name="classificacao" label="Classificação" /></> : null}
    {type === "atividades" ? <><Field name="codigo" label="Código" required /><Field name="descricao" label="Descrição" required wide /><Field name="porte" label="Porte" required /><Field name="potencial" label="Potencial poluidor" required /><Field name="licencas" label="Licenças, separadas por vírgula" required /><Field name="documentos" label="Documentos, separados por vírgula" required wide /></> : null}
    {type === "taxas" ? <><Select name="atividadeId" label="Atividade" options={state.atividades.map((item) => [item.id, item.descricao])} /><Field name="licenca" label="Licença" required /><Field name="porte" label="Porte" required /><Field name="valor" label="Valor em reais" type="number" required /></> : null}
    {type === "usuarios" ? <><Field name="nome" label="Nome" required /><Field name="email" label="E-mail" type="email" required /><Field name="senha" label="Senha temporária" type="password" required /><label>Perfil<select value={role} onChange={(event) => setRole(event.target.value as Usuario["perfil"])}>{["Administrador", "Analista", "Fiscal", "Empreendedor"].map((item) => <option key={item}>{item}</option>)}</select></label>{role === "Empreendedor" ? <Select name="empreendedorId" label="Vínculo com empreendedor" options={state.empreendedores.map((item) => [item.id, item.nome])} /> : null}</> : null}
    {type === "modelos" ? <><Field name="nome" label="Nome" required /><Select name="tipo" label="Tipo" options={["Licença", "Parecer", "Notificação", "Certidão", "Autorização"].map((item) => [item, item])} /><label className="wide">Conteúdo<textarea name="conteudo" required rows={10} placeholder="Use variáveis como {{processo}} e {{empreendimento}}" /></label></> : null}
    {type === "fiscalizacao" ? <><Select name="processoId" label="Processo" options={state.processos.map((item) => [item.id, item.numero])} /><Select name="fiscalId" label="Fiscal" options={state.usuarios.filter((item) => item.perfil === "Fiscal").map((item) => [item.id, item.nome])} /><Select name="tipo" label="Tipo" options={["Vistoria", "Auto de infração", "Embargo", "Notificação"].map((item) => [item, item])} /><Field name="data" label="Data" type="datetime-local" required /><Field name="latitude" label="Latitude" type="number" /><Field name="longitude" label="Longitude" type="number" /><label className="wide">Relatório<textarea name="relatorio" rows={5} required /></label></> : null}
    {error ? <div className="field-error wide" role="alert">{error}</div> : null}<footer className="form-footer"><Button variant="secondary" type="button" onClick={onClose}>Cancelar</Button><Button loading={saving} type="submit"><Save />Salvar</Button></footer>
  </form></Modal>;
}

function Field({ name, label, wide, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { name: string; label: string; wide?: boolean }) { return <label className={wide ? "wide" : ""}>{label}<input name={name} {...props} /></label>; }
function Select({ name, label, options }: { name: string; label: string; options: string[][] }) { return <label>{label}<select name={name} required><option value="">Selecione</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const maskDocument = (value: string) => value.length > 6 ? `${value.slice(0, 3)}••••${value.slice(-3)}` : "Documento protegido";

export function ReportsPage() {
  const { state } = useApp(); const [status, setStatus] = useState("Todos"); const rows = useMemo(() => state.processos.filter((item) => status === "Todos" || item.status === status), [state.processos, status]);
  const csv = () => { const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; const content = "\ufeff" + [["Processo", "Protocolo", "Tipo", "Situação", "Abertura", "Prazo"], ...rows.map((item) => [item.numero, item.protocolo, item.tipoLicenca, item.status, item.abertura, item.prazo])].map((line) => line.map(escape).join(";")).join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); link.download = `relatorio-licenciamento-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <><PageHeader title="Relatórios" description="Indicadores gerenciais e dados filtrados." actions={<><Button variant="secondary" onClick={() => window.print()}><Printer />Imprimir</Button><Button onClick={csv}><Download />Exportar CSV</Button></>} /><div className="filter-bar"><label>Situação<select value={status} onChange={(event) => setStatus(event.target.value)}><option>Todos</option>{[...new Set(state.processos.map((item) => item.status))].map((item) => <option key={item}>{item}</option>)}</select></label></div><section className="metrics-grid"><article className="metric"><div><strong>{rows.length}</strong><span>Processos no filtro</span></div></article><article className="metric"><div><strong>{rows.filter((item) => item.licencaEmitida).length}</strong><span>Licenças emitidas</span></div></article><article className="metric"><div><strong>{rows.filter((item) => item.status === "Em análise").length}</strong><span>Em análise</span></div></article></section><div className="data-table"><table><thead><tr><th>Processo</th><th>Tipo</th><th>Situação</th><th>Abertura</th><th>Prazo</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td>{item.numero}</td><td>{item.tipoLicenca}</td><td><StatusBadge>{item.status}</StatusBadge></td><td>{item.abertura}</td><td>{item.prazo}</td></tr>)}</tbody></table></div></>;
}

export function SettingsPage() {
  const { state, session, refresh } = useApp(); const [draft, setDraft] = useState(state.configuracao); const [saving, setSaving] = useState(false); const dirty = JSON.stringify(draft) !== JSON.stringify(state.configuracao);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!session || !dirty) return; setSaving(true); await saveSettingsApi(session.token, draft); await refresh(); setSaving(false); };
  return <><PageHeader title="Configurações" description="Parâmetros institucionais, prazos, uploads e consulta pública." /><form className="settings-form" onSubmit={submit}><section><h2>Identidade institucional</h2><Field name="orgao" label="Órgão" value={draft.orgao} onChange={(event) => setDraft({ ...draft, orgao: event.target.value })} /><Field name="municipio" label="Município" value={draft.municipio} onChange={(event) => setDraft({ ...draft, municipio: event.target.value })} /></section><section><h2>Prazos</h2><Field name="prazo" label="Prazo de análise, em dias" type="number" min={1} max={365} value={draft.prazoAnaliseDias} onChange={(event) => setDraft({ ...draft, prazoAnaliseDias: Number(event.target.value) })} /><Field name="alerta" label="Alerta de vencimento, em dias" type="number" min={1} max={365} value={draft.alertaVencimentoDias} onChange={(event) => setDraft({ ...draft, alertaVencimentoDias: Number(event.target.value) })} /></section><section><h2>Uploads e consulta pública</h2><Field name="upload" label="Limite por arquivo, em MB" type="number" min={1} max={100} value={draft.tamanhoMaxUploadMb} onChange={(event) => setDraft({ ...draft, tamanhoMaxUploadMb: Number(event.target.value) })} /><label className="check"><input type="checkbox" checked={draft.consultaPublicaAtiva} onChange={(event) => setDraft({ ...draft, consultaPublicaAtiva: event.target.checked })} />Permitir consulta pública</label></section><footer><span>{dirty ? "Alterações não salvas" : "Configurações atualizadas"}</span><Button loading={saving} disabled={!dirty}><Save />Salvar configurações</Button></footer></form></>;
}
