ALTER TYPE "LicenseType" ADD VALUE IF NOT EXISTS 'LUA';
ALTER TYPE "LicenseType" ADD VALUE IF NOT EXISTS 'LUAR';
ALTER TYPE "LicenseType" ADD VALUE IF NOT EXISTS 'RELUA';
ALTER TYPE "LicenseType" ADD VALUE IF NOT EXISTS 'AQC';
ALTER TYPE "LicenseType" ADD VALUE IF NOT EXISTS 'LOC';
