import { Calendar, ChevronLeft, ChevronRight, Copy, FilePlus2, FilterX, MapPin, Plus, Printer, Upload } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { createProcessApi, getUserErrorMessage, sendProcessMessageApi, uploadDocumentApi } from "../../api";
import { useApp } from "../../app/providers";
import { Button, EmptyState, Modal, PageHeader, SearchField, Skeleton, StatusBadge } from "../../components/ui";
import type { Processo } from "../../types";

export function ProcessesPage() {
  const { state, session, loading, refresh } = useApp(); const { processId } = useParams(); const navigate = useNavigate();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("Todos"); const [license, setLicense] = useState("Todos"); const [sort, setSort] = useState("recentes"); const [page, setPage] = useState(1); const [perPage, setPerPage] = useState(10); const [wizard, setWizard] = useState(false);
  const allowedCreate = session?.perfil === "Administrador" || session?.perfil === "Analista" || session?.perfil === "Empreendedor";
  const rows = useMemo(() => state.processos.filter((item) => {
    const enterprise = state.empreendimentos.find((entry) => entry.id === item.empreendimentoId)?.nome ?? "";
    return (!query || `${item.numero} ${item.protocolo} ${enterprise}`.toLowerCase().includes(query.toLowerCase())) && (status === "Todos" || item.status === status) && (license === "Todos" || item.tipoLicenca === license);
  }).sort((a, b) => sort === "numero" ? a.numero.localeCompare(b.numero) : b.abertura.localeCompare(a.abertura)), [state, query, status, license, sort]);
  const pages = Math.max(1, Math.ceil(rows.length / perPage)); const visible = rows.slice((page - 1) * perPage, page * perPage); const selected = state.processos.find((item) => item.id === processId);
  return <><PageHeader title="Processos" description="Pesquise, filtre e acompanhe solicitações de licenciamento." actions={allowedCreate ? <Button onClick={() => setWizard(true)}><Plus />Nova solicitação</Button> : null} />
    <section className="filter-bar"><SearchField value={query} onChange={(value) => { setQuery(value); setPage(1); }} placeholder="Buscar processo, protocolo ou empreendimento" /><label>Situação<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option>Todos</option>{[...new Set(state.processos.map((item) => item.status))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Tipo<select value={license} onChange={(event) => setLicense(event.target.value)}><option>Todos</option>{[...new Set(state.processos.map((item) => item.tipoLicenca))].map((item) => <option key={item}>{item}</option>)}</select></label><label>Ordenar<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recentes">Mais recentes</option><option value="numero">Número</option></select></label><button className="button button--ghost" onClick={() => { setQuery(""); setStatus("Todos"); setLicense("Todos"); }}><FilterX />Limpar</button></section>
    <div className="results-summary"><strong>{rows.length}</strong> resultado(s)</div>{loading ? <Skeleton rows={6} /> : visible.length ? <div className="data-table"><table><thead><tr><th>Processo</th><th>Protocolo</th><th>Tipo</th><th>Empreendimento</th><th>Responsável</th><th>Abertura</th><th>Prazo</th><th>Situação</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{visible.map((item) => <ProcessRow key={item.id} item={item} state={state} onOpen={() => navigate(`/processos/${item.id}`)} />)}</tbody></table></div> : <EmptyState title="Nenhum processo encontrado" />}
    <footer className="pagination"><label>Itens por página<select value={perPage} onChange={(event) => { setPerPage(Number(event.target.value)); setPage(1); }}>{[10, 25, 50].map((value) => <option key={value}>{value}</option>)}</select></label><span>Página {page} de {pages}</span><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} aria-label="Página anterior"><ChevronLeft /></button><button disabled={page === pages} onClick={() => setPage((value) => value + 1)} aria-label="Próxima página"><ChevronRight /></button></footer>
    {selected ? <ProcessDrawer process={selected} onClose={() => navigate("/processos")} /> : null}{wizard ? <NewProcessWizard onClose={() => setWizard(false)} /> : null}</>;
}

function ProcessRow({ item, state, onOpen }: { item: Processo; state: ReturnType<typeof useApp>["state"]; onOpen(): void }) {
  const enterprise = state.empreendimentos.find((entry) => entry.id === item.empreendimentoId)?.nome ?? "-";
  return <tr><td data-label="Processo"><button className="table-link" onClick={onOpen}>{item.numero}</button></td><td data-label="Protocolo">{item.protocolo}</td><td data-label="Tipo">{item.tipoLicenca}</td><td data-label="Empreendimento">{enterprise}</td><td data-label="Responsável">{item.analista}</td><td data-label="Abertura">{item.abertura}</td><td data-label="Prazo">{item.prazo}</td><td data-label="Situação"><StatusBadge>{item.status}</StatusBadge></td><td data-label="Ação"><Button variant="ghost" onClick={onOpen}>Ver detalhes</Button></td></tr>;
}

function ProcessDrawer({ process, onClose }: { process: Processo; onClose(): void }) {
  const { state, session, refresh } = useApp(); const [tab, setTab] = useState("visao"); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const enterprise = state.empreendimentos.find((item) => item.id === process.empreendimentoId); const entrepreneur = state.empreendedores.find((item) => item.id === process.empreendedorId);
  const tabs = ["visao", "andamento", "documentos", "mensagens", "fiscalizacoes", "pareceres", "licenca", ...(session?.perfil === "Administrador" ? ["auditoria"] : [])];
  const send = async (event: FormEvent) => { event.preventDefault(); if (!session || sending) return; setSending(true); try { await sendProcessMessageApi(session.token, process.id, message); setMessage(""); await refresh(); } finally { setSending(false); } };
  return <Modal title={`Processo ${process.numero}`} onClose={onClose}><div className="drawer-summary"><StatusBadge>{process.status}</StatusBadge><span>{process.tipoLicenca}</span><span><Calendar />Prazo: {process.prazo}</span></div><div className="detail-tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} key={item} onClick={() => setTab(item)}>{({ visao: "Visão geral", andamento: "Andamento", documentos: "Documentos", mensagens: "Mensagens", fiscalizacoes: "Fiscalizações", pareceres: "Pareceres", licenca: "Licença emitida", auditoria: "Auditoria" } as Record<string, string>)[item]}</button>)}</div><section className="detail-content">
    {tab === "visao" ? <dl className="detail-grid"><div><dt>Protocolo</dt><dd>{process.protocolo}</dd></div><div><dt>Empreendedor</dt><dd>{entrepreneur?.nome ?? "-"}</dd></div><div><dt>Empreendimento</dt><dd>{enterprise?.nome ?? "-"}</dd></div><div><dt>Responsável</dt><dd>{process.analista}</dd></div><div><dt>Abertura</dt><dd>{process.abertura}</dd></div><div><dt>Localização</dt><dd>{enterprise?.latitude ? <a target="_blank" rel="noreferrer" href={`https://www.openstreetmap.org/?mlat=${enterprise.latitude}&mlon=${enterprise.longitude}`}><MapPin />Abrir mapa</a> : "Não informada"}</dd></div></dl> : null}
    {tab === "andamento" ? <ol className="timeline">{process.timeline.map((item) => <li className={item.current ? "current" : ""} key={item.id}><i /> <div><strong>{item.label}</strong><span>{item.actor} · {item.date}</span></div></li>)}</ol> : null}
    {tab === "documentos" ? <div className="document-list">{process.documentos.map((doc) => <article key={doc.id}><div><strong>{doc.nome}</strong><StatusBadge>{doc.status}</StatusBadge></div>{doc.observacao ? <p>{doc.observacao}</p> : null}{doc.status === "Pendente" || doc.status === "Recusado" ? <label className="button button--secondary"><Upload />Enviar arquivo<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={async (event) => { const file = event.target.files?.[0]; if (file && session) { await uploadDocumentApi(session.token, doc.id, file); await refresh(); } }} /></label> : null}</article>)}</div> : null}
    {tab === "mensagens" ? <><div className="message-list">{process.mensagens.map((item) => <article key={item.id}><strong>{item.autor}</strong><p>{item.texto}</p><time>{item.data}</time></article>)}</div><form className="message-form" onSubmit={send}><label htmlFor="message">Nova mensagem</label><textarea id="message" value={message} onChange={(event) => setMessage(event.target.value)} minLength={3} required /><Button loading={sending}>Enviar mensagem</Button></form></> : null}
    {tab === "fiscalizacoes" ? <div className="record-list">{state.fiscalizacoes.filter((item) => item.processoId === process.id).map((item) => <article key={item.id}><strong>{item.tipo}</strong><span>{item.data} · {item.fiscal}</span><StatusBadge>{item.status ?? "Agendada"}</StatusBadge></article>)}</div> : null}
    {tab === "pareceres" ? <p>{process.parecer ?? "Nenhum parecer emitido."}</p> : null}{tab === "licenca" ? <p>{process.licencaEmitida ? `${process.licencaEmitida.numero} · validade ${process.licencaEmitida.validade}` : "Licença ainda não emitida."}</p> : null}{tab === "auditoria" ? <div className="record-list">{state.auditoria.filter((item) => item.entidade.includes(process.id) || item.entidade.includes(process.numero)).map((item) => <article key={item.id}>{item.data} · {item.acao} · {item.usuario}</article>)}</div> : null}</section></Modal>;
}

function NewProcessWizard({ onClose }: { onClose(): void }) {
  const { state, session, refresh } = useApp(); const [step, setStep] = useState(1); const [enterpriseId, setEnterpriseId] = useState(""); const [license, setLicense] = useState(""); const [saving, setSaving] = useState(false); const [created, setCreated] = useState(""); const [error, setError] = useState(""); const enterprise = state.empreendimentos.find((item) => item.id === enterpriseId); const activity = state.atividades.find((item) => item.id === enterprise?.atividadeId);
  const submit = async () => { if (!session || !enterprise || saving) return; setSaving(true); try { const result = await createProcessApi(session.token, enterprise, license); setCreated(result.number); await refresh(); setStep(5); } catch (cause) { setError(getUserErrorMessage(cause)); } finally { setSaving(false); } };
  return <Modal title="Nova solicitação" onClose={onClose}><div className="wizard-steps">{[1, 2, 3, 4, 5].map((item) => <span className={step >= item ? "active" : ""} key={item}>{item}</span>)}</div><div className="wizard-body">{step === 1 ? <><h3>Empreendedor e empreendimento</h3><label>Empreendimento<select value={enterpriseId} onChange={(event) => setEnterpriseId(event.target.value)}><option value="">Selecione</option>{state.empreendimentos.map((item) => <option value={item.id} key={item.id}>{item.nome}</option>)}</select></label></> : null}{step === 2 ? <><h3>Tipo de licença</h3><div className="choice-grid">{(activity?.licencas ?? []).map((item) => <button className={license === item ? "active" : ""} onClick={() => setLicense(item)} key={item}><strong>{item}</strong><span>Licença ambiental</span></button>)}</div></> : null}{step === 3 ? <><h3>Documentos necessários</h3><ul className="check-list">{(activity?.documentos ?? []).map((item) => <li key={item}><FilePlus2 />{item}<span>Obrigatório · PDF/JPG</span></li>)}</ul></> : null}{step === 4 ? <><h3>Revisão</h3><dl className="detail-grid"><div><dt>Empreendimento</dt><dd>{enterprise?.nome}</dd></div><div><dt>Tipo</dt><dd>{license}</dd></div><div><dt>Documentos</dt><dd>{activity?.documentos.length ?? 0} necessários</dd></div></dl>{error ? <div className="field-error">{error}</div> : null}</> : null}{step === 5 ? <div className="success-state"><strong>Solicitação protocolada</strong><span>{created}</span><div><Button variant="secondary" onClick={() => navigator.clipboard.writeText(created)}><Copy />Copiar</Button><Button variant="secondary" onClick={() => window.print()}><Printer />Imprimir</Button></div></div> : null}</div><footer className="wizard-footer">{step > 1 && step < 5 ? <Button variant="secondary" onClick={() => setStep((value) => value - 1)}>Voltar</Button> : null}{step < 4 ? <Button disabled={(step === 1 && !enterpriseId) || (step === 2 && !license)} onClick={() => setStep((value) => value + 1)}>Continuar</Button> : null}{step === 4 ? <Button loading={saving} onClick={submit}>Confirmar solicitação</Button> : null}{step === 5 ? <Button onClick={onClose}>Acessar processos</Button> : null}</footer></Modal>;
}
